---
- hosts: production
  vars_files:
    - group_vars/project-hosts.yml
    - group_vars/vars_vault.yml
  become: true
  become_user: "{{ username }}"
  roles:
    - django
    - frontend

- hosts: production
  become: true
  vars_files:
    - group_vars/project-hosts.yml
    - group_vars/vars_vault.yml
  tasks:
    - name: restart site in supervisor
      supervisorctl: name={{ project_slug }}-gunicorn state=restarted

    - name: restart postgresql
      service: name=postgresql state=restarted enabled=yes

    - name: restart nginx
      service: name=nginx state=restarted enabled=yes
