---

- name: updating the system
  apt: update_cache=yes cache_valid_time=86400

# - name: install nodejs 7* repo
#   shell: curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -

- name: install packages
  apt: pkg="{{ item.name }}" state=present force=yes
  with_items:
    - name: python3-pip
    - name: python3-dev
    - name: postgresql-{{ pg_version }}
    - name: postgresql-contrib
    - name: npm
    - name: git
    - name: libpq-dev
    - name: python-psycopg2
    - name: language-pack-ru-base
    - name: build-essential
    - name: nodejs-legacy

- name: reconfigure locales
  shell: dpkg-reconfigure language-pack-ru-base

- name: install virtualenv
  pip:
    executable: pip3
    name: virtualenv

- name: create linux user
  user: name={{ username }} shell=/bin/bash home={{ user_homedir }} password={{ user_crypt_password }}

- name: chown homedir
  file:
    path: "{{ user_homedir }}"
    owner: "{{ username }}"

- name: Create Postgresql database
  become: yes
  become_user: postgres
  postgresql_db: >
    name={{ postgresql_database }}
    lc_collate=en_US.UTF-8
    lc_ctype=en_US.UTF-8
    encoding=UTF-8
    state=present
  notify:
    - restart postgresql

- name: Create Postgresql user
  become: yes
  become_user: postgres
  postgresql_user: >
    db={{ postgresql_database }}
    name={{ postgresql_user }}
    password={{ postgresql_user_password }}
    priv=ALL
    state=present
  notify:
    - restart postgresql
