---
- name: git pull
  git:
    repo: 'https://github.com/pyshopml/jobs-backend.git'
    dest: "{{ backend_dir }}"
    version: master

- name: create static directory
  file: path={{ backend_dir }}/jobs_backend/static state=directory

- name: create virtualenv
  pip:
    virtualenv: "{{ backend_dir }}/venv"
    requirements: "{{ requirements }}"

- name: copy .env
  template: src=.env.j2 dest={{ backend_dir }}/config/settings/.env

- name: migrate database
  django_manage: command=migrate virtualenv={{ env }} app_path={{ backend_dir }} settings=config.settings.production

- name: collectstatic
  django_manage: command=collectstatic virtualenv={{ env }} app_path={{ backend_dir }} settings=config.settings.production
