---
- name: git pull
  git:
    repo: 'https://github.com/pyshopml/jobs-backend.git'
    dest: "{{ backend_dir }}"
    version: master

- name: create logs directory
  file: path={{ project_dir }}/logs state=directory

- name: crasdeate logs directory
  file: path={{ backend_dir }}/jobs_backend/static state=directory


- name: create virtualenv
  pip:
    virtualenv: "{{ backend_dir }}/venv"
    requirements: "{{ requirements }}"

- name: copy .env
  template: src=.env dest={{ backend_dir }}/config/settings/.env

- name: migrate database
  django_manage: command=migrate virtualenv={{ env }} app_path={{ backend_dir }}

- name: collectstatic
  django_manage: command=collectstatic virtualenv={{ env }} app_path={{ backend_dir }}

# - name: create media directory
#   file: path={{ project_dir }}/media state=directory
#
# - name: create `uploads` directory
#   file: path={{ project_dir }}/media/uploads state=directory
